Cadeteria/Models/Cadete.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cadeteria.Models
{
    public class Cadete : Persona
    {
        public List<Pedido> listadoPedidos;
        public int Id;
        protected static int id = 0;

        public void JornalACobrar()
        {
            
        }

        public Cadete()
        {
            this.Id=id++;
            this.listadoPedidos=new List<Pedido>();
        }

        public void recibirPedido(Pedido pedido)
        {
            listadoPedidos.Add(pedido);
        }
    }
}

Cadeteria/Models/CadeteriaWeb.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cadeteria.Models
{
    public class CadeteriaWeb
    {
    protected string nombre;
    protected string telefono;
    public List<Cadete> ListadoCadetes;

    public CadeteriaWeb()
    {
        ListadoCadetes = new List<Cadete>();
    }

    public void AgregarCadete(string nombre,string telefono,string direccion)
    {
        var cadete = new Cadete();
        cadete.Nombre = nombre;
        cadete.Telefono = telefono;
        cadete.Direccion = direccion;
        ListadoCadetes.Add(cadete);
    }

    public void RemoverCadete(int id)
    {
        var cadeteBorrable = ListadoCadetes.Find(cadete => cadete.Id == id);
        ListadoCadetes.Remove(cadeteBorrable);
    }

    }
}

Cadeteria/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cadeteria.Models
{
    public class Cliente : Persona
    {
         public string DatoReferenciaDireccion;
        public int cantPedidos;

        public Cliente()
        {
            this.DatoReferenciaDireccion="referencias";
            cantPedidos= 0;
        }
    }
}

Cadeteria/Models/ErrorViewModel.cs
namespace Cadeteria.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Cadeteria/Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cadeteria.Models
{
    public class Pedido
    {
        public int nro;
        public string obs;
        public Cliente cliente;
        public string estado;

        public Pedido(Cliente cliente)
        {
            this.obs = "a";
            this.cliente = new Cliente();
            this.estado = "Pendiente";
        }
    }
}

Cadeteria/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cadeteria.Models
{
    public class Persona
    {
        private string nombre;
        private string direccion;
        private string telefono;

        public string Nombre { get => nombre; set => nombre = value; }
        public string Direccion { get => direccion; set => direccion = value; }
        public string Telefono { get => telefono; set => telefono = value; }

        public Persona()
        {
        }
    }
}

Cadeteria/Controllers/CadeteriaHubController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Cadeteria.Models;

namespace Cadeteria.Controllers;

public class CadeteriaHubController : Controller
{
    private readonly ILogger<CadeteriaHubController> _logger;
    private static CadeteriaWeb cadeteria = new CadeteriaWeb();

    public CadeteriaHubController(ILogger<CadeteriaHubController> logger)
    {
        _logger = logger;
    }

    [HttpPost]

    public IActionResult Carga(string nombre)
    {
        cadeteria.AgregarCadete(Request.Form["Nombre"],Request.Form["Telefono"],Request.Form["Direccion"]);
        return Redirect("Listado");
    }

    [HttpGet]
    public IActionResult Borrar(int id)
    {
        cadeteria.RemoverCadete(id);
        return Redirect("listado");
    }

    public IActionResult Listado()
    {
        return View(cadeteria.ListadoCadetes);
    }

    public IActionResult AltaCadete()
    {
        return View();
    }

    public IActionResult BajaCadete()
    {
        return View(cadeteria.ListadoCadetes);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Cadeteria/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Cadeteria.Models;

namespace Cadeteria.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Cadeteria/Views/CadeteriaHub/AltaCadete.cshtml
@{
    ViewData["Title"] = "AltaCadete";
}

<h1>@ViewData["Title"]</h1>

<div>
    @using(Html.BeginForm("Carga", "CadeteriaHub", FormMethod.Post))
    {
        <h3>Nombre: </h3>
        <input type="text" name="Nombre">
        <h3>Telefono: </h3>
        <input type="phone" name="Telefono">
        <h3>Direccion: </h3>
        <input type="text" name="Direccion">
        <input type="submit" value="Enviar" class="btn btn-primary">
    }
</div>

Cadeteria/Views/CadeteriaHub/BajaCadete.cshtml
@model List<Cadeteria.Models.Cadete>
@{
    ViewData["Title"] = "BajaCadete";
}

<h1>@ViewData["Title"]</h1>

<div>
    <table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Telefono</th>
            <th>Direccion</th>
            <th>CantPedidos</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cadete in Model)
        {
            <tr>
                <tr>
                <td>@cadete.Id</td>
                <td>@cadete.Nombre</td>
                <td>@cadete.Telefono</td>
                <td>@cadete.Direccion</td>
                <td>@cadete.listadoPedidos.Count()</td>
            </tr>
                <td>
                    @using(Html.BeginForm("Borrar", "CadeteriaHub", FormMethod.Get))
                    {
                        <input type="hidden" name="id" value=@cadete.Id >
                        <input type="submit" value="Borrar" class="btn btn-primary">
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

Cadeteria/Views/CadeteriaHub/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Cadeteria/Views/CadeteriaHub/Listado.cshtml
@model List<Cadeteria.Models.Cadete>
@{
    ViewData["Title"] = "Listado";
}

<h1>@ViewData["Title"]</h1>

<table class="table table-bordered table-hover">
    <thead class="thead-dark">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Telefono</th>
            <th>Direccion</th>
            <th>CantPedidos</th>
        </tr>
    </thead>
    <tbody class="table-striped" >
        @foreach (var cadete in Model)
        {
            <tr>
                <td>@cadete.Id</td>
                <td>@cadete.Nombre</td>
                <td>@cadete.Telefono</td>
                <td>@cadete.Direccion</td>
                <td>@cadete.listadoPedidos.Count()</td>
            </tr>
        }
    </tbody>
</table>

<section class="btn-group">
        <a href="AltaCadete" class="btn btn-primary btn-sm">AltaCadete</a>
        <a href="BajaCadete" class="btn btn-primary btn-sm">BajaCadete</a>
</section>

Cadeteria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cadeteria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cadeteria.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cadeteria</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CadeteriaHub" asp-action="Listado">Listado</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Cadeteria - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>